### PR TITLE
Added message deletion in clean command

### LINKED ISSUE #175: Remove clean command after being used
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information
 

**Platform**
Discord

**Describe the feature**
Remove clean command like 5 seconds after being used, same for the message that has the command 

**How the feature is useful**
Looks nicer

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

### PR DESCRIPTION
**Pull request by MiginsMC**
Deletes the call and response to/from the bot when using the `!clean` command. If you don't like this change, that' all g this pr took me like 2 seconds so no biggie if you close it.
Closes [#175](https://github.com/Minehut/Meta/issues/175)

### CODE REVIEW

**Comment by theminecoder** [comment]
I think if you add a delay to this (maybe 5 seconds) then it would make sense, as it would currently just send the message then instantly yeet it. Otherwise looks good 👍

**Review by theminecoder — CHANGES_REQUESTED** [review]
I think if you add a delay to this (maybe 5 seconds) then it would make sense, as it would currently just send the message then instantly yeet it. Otherwise looks good 👍

**Comment by jellz** [comment]
@theminecoder The `timeout` option in the [Message#delete(...)](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=delete) function is the number of MS to wait before deleting. It wouldn't have been instant since it was used in this change.

**Review by jellz — CHANGES_REQUESTED** [review]
Please run Prettier on this file, it doesn't seem to be formatted correctly (`({timeout: 5000})` -> `({ timeout: 5000 })`)

**Review by theminecoder — APPROVED** [review]
Ok, I am going to pre-approve this provided the formatting happens. Will merge once we update how we deploy this thing internally

**Comment by MiginsMC** [comment]
> Please run Prettier on this file, it doesn't seem to be formatted correctly (`({timeout: 5000})` -> `({ timeout: 5000 })`)

haha forgot about prettier

**Comment by MiginsMC** [comment]
I didn't do it right, then I reverted it and then I pulled master and then I HOPEFULLY did it right, thanks.
as we can see I'm very good at this :eyes:

**Pull request merged**
