### PR TITLE
Update some important filters

### PR DESCRIPTION
**Pull request by MiginsMC**
This pr will add the following to the filter:
- d!ck
- dogshit
- $hit

It will also remove the following from the filter:
- analytic
- analytics
- analytical
- analogy
- negotiable
- neglect
- neglectable
- neglected
- negative

I tried to only add words that were clearly filterable/unfilterable to avoid making any big decisions that would be better made by higher-ups. If any other words need to be added, feel free to comment or dm me on Discord :)

### CODE REVIEW

**Comment by muelr** [comment]
**Block** 

kcuf
:middle_finger:
retartd
reta rd
f.u.c.k
shi1t
$hit
fúck
minefuck
virgin
virginity
paki
hubporn
f*ck
dumbass
milf
sped
fu,ck
f_u_ck
N\I\G\G\A
sshit
D I C K
https://zoom.us/
sh*t
Brothel
d!ck
dc!k
a.ss
thot

**Unblock** 

nibble
analysing
analytics
digest
cocker spaniel
cocky
nigeria
this is bob
negl
shilba
player's hitbox
neglected
¯\_(ツ)_/¯
sigma
0.
bit challenging

Please and ty!

**Comment by MiginsMC** [comment]
All those above (except those which weren't actually blocked) should be complete. There were quite a few so if I missed one or if I made a mistake, please review!! Thanks.

**Review by draem — APPROVED** [review]

**Comment by muelr** [comment]
**Block**

- chode
- https://tornadus.net/orange (Discord crasher)
- what da fawk
- p0rnhub

ty!!

**Review by Bloxs — APPROVED** [review]
Looks good to me

**Review by theminecoder — APPROVED** [review]

**Pull request merged**
