### PR TITLE
Remove trailing comma

### PR DESCRIPTION
**Pull request by DebitCardz**

### CODE REVIEW

**Comment by Sniped** [comment]
I don't see the point in removing the trailing comma here. The formatter that is used for the project, Prettier, actually adds these by default, so if we were to remove the trailing comma here, we would probably have to remove the trailing commas **everywhere** in the codebase, which would mostly be prominent in `guildConfigs.ts`. A few examples of this are shown [here](https://github.com/Minehut/MinehutBOT/blob/master/src/guild/config/guildConfigs.ts#L26), [here](https://github.com/Minehut/MinehutBOT/blob/master/src/guild/config/guildConfigs.ts#L26), and [here](https://github.com/Minehut/MinehutBOT/blob/master/src/guild/config/guildConfigs.ts#L45).

**Review by unlimitedcoder2 — APPROVED** [review]
LGTM

**Comment by DebitCardz** [comment]
> I don't see the point in removing the trailing comma here. The formatter that is used for the project, Prettier, actually adds these by default, so if we were to remove the trailing comma here, we would probably have to remove the trailing commas **everywhere** in the codebase, which would mostly be prominent in `guildConfigs.ts`. A few examples of this are shown [here](https://github.com/Minehut/MinehutBOT/blob/master/src/guild/config/guildConfigs.ts#L26), [here](https://github.com/Minehut/MinehutBOT/blob/master/src/guild/config/guildConfigs.ts#L26), and [here](https://github.com/Minehut/MinehutBOT/blob/master/src/guild/config/guildConfigs.ts#L45).

prettier wack.

**Comment by jellz** [comment]
What’s the purpose of this PR?

**Comment by DebitCardz** [comment]
> What’s the purpose of this PR?

to remove a trailing comma as said in the title.

**Pull request closed without merging**
