### PR TITLE
Add pagination to single tag section listing and make sections caps insensitive

### PR DESCRIPTION
**Pull request by lilrosalyn**
!tags <section> is now paginated
!tags <section> is now caps insensitive

### CODE REVIEW

**Comment by lilrosalyn** [comment]
Don't merge yet :) fixing some naming inconsistencies

**Comment by lilrosalyn** [comment]
Inconsistencies have been fixed

**Comment by theminecoder** [comment]
@honkling Can you address ^ and rebase/merge in the changes in master and then request a review? Wanna close this off soon :)

**Comment by jellz** [comment]
The first part of Migins' comment was already addressed in #102, just the case-sensitivity issue now

**Comment by lilrosalyn** [comment]
Do we already have a function for making the first letter of a string uppercase and the rest of the string lowercase? I tried using startCase from lodash but it doesn't make the rest of the string lowercase like I hoped. I'm using "section[0].toUpperCase() + section.substr(1).toLowerCase()" currently, but I'd like to make sure I'm not missing something.

**Comment by jellz** [comment]
> Do we already have a function for making the first letter of a string uppercase and the rest of the string lowercase? I tried using startCase from lodash but it doesn't make the rest of the string lowercase like I hoped. I'm using "section[0].toUpperCase() + section.substr(1).toLowerCase()" currently, but I'd like to make sure I'm not missing something.

You might be looking for [lodash capitalize](https://lodash.com/docs/#capitalize)

**Comment by lilrosalyn** [comment]
> You might be looking for [lodash capitalize](https://lodash.com/docs/#capitalize)

Yes, that's perfect. Thanks

**Comment by lilrosalyn** [comment]
I'm gonna be honest I had no idea what I was doing when rebasing, but I don't think I did it right. I'll just close this PR for now and I'll (or somebody else if they beat me to it) add pagination and caps insensitivity again at a later time, but this PR is a mess and I don't really know how to fix it.

**Pull request closed without merging**
